### ISSUE TITLE
DESIGN_GUI_Class

### ISSUE THREAD

**Issue by marlinroberts21** [acevedo88/HU-CS-217-Team-BeardedGlory#7]
Overall structure and implementation of the GUI class

DOD: Basic structure and design of the GUI agreed upon by team

**Comment by acevedo88** [comment]
![IMG-0372.JPG](https://images.zenhubusercontent.com/5d0910e028baa551d628a416/41e5f6d8-d689-486a-b801-298ec16a950a)
